version: "3.8"
services:
   backend:
     container_name: backend
     build: ./backend
     depends_on:
        - postgres
     env_file:
        - ./.env
     links:
       - postgres
       - postgres-test
     ports:
       - "8000:8000"
     volumes:
       - ./media/:/backend/media/
       - ./log/:/backend/log/

   frontend:
     container_name: frontend
     build: ./frontend
     links:
       - backend
     ports:
       - "3000:3000"
     volumes:
       - ./media/:/frontend/public/media/

   postgres:
     container_name: db_postgres
     image: postgres:12
     env_file:
        - ./.env
     ports:
        - "5432:5432"
     volumes:
        - ./data/:/var/lib/postgresql/data

   postgres-test:
     container_name: db_test
     image: postgres:12
     environment:
        - POSTGRES_PASSWORD=test
        - POSTGRES_USER=test
     ports:
        - "5433:5432"
     volumes:
        - ./data_test/:/var/lib/postgresql/data


